// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"exampleApp/internal/domain/wallet"

	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletService creates a new instance of MockWalletService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletService {
	mock := &MockWalletService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletService is an autogenerated mock type for the WalletService type
type MockWalletService struct {
	mock.Mock
}

type MockWalletService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletService) EXPECT() *MockWalletService_Expecter {
	return &MockWalletService_Expecter{mock: &_m.Mock}
}

// ChageAmount provides a mock function for the type MockWalletService
func (_mock *MockWalletService) ChageAmount(context1 context.Context, walletRequest wallet.WalletRequest) (wallet.Wallet, error) {
	ret := _mock.Called(context1, walletRequest)

	if len(ret) == 0 {
		panic("no return value specified for ChageAmount")
	}

	var r0 wallet.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wallet.WalletRequest) (wallet.Wallet, error)); ok {
		return returnFunc(context1, walletRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wallet.WalletRequest) wallet.Wallet); ok {
		r0 = returnFunc(context1, walletRequest)
	} else {
		r0 = ret.Get(0).(wallet.Wallet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wallet.WalletRequest) error); ok {
		r1 = returnFunc(context1, walletRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletService_ChageAmount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChageAmount'
type MockWalletService_ChageAmount_Call struct {
	*mock.Call
}

// ChageAmount is a helper method to define mock.On call
//   - context1 context.Context
//   - walletRequest wallet.WalletRequest
func (_e *MockWalletService_Expecter) ChageAmount(context1 any, walletRequest any) *MockWalletService_ChageAmount_Call {
	return &MockWalletService_ChageAmount_Call{Call: _e.mock.On("ChageAmount", context1, walletRequest)}
}

func (_c *MockWalletService_ChageAmount_Call) Run(run func(context1 context.Context, walletRequest wallet.WalletRequest)) *MockWalletService_ChageAmount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wallet.WalletRequest
		if args[1] != nil {
			arg1 = args[1].(wallet.WalletRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletService_ChageAmount_Call) Return(wallet1 wallet.Wallet, err error) *MockWalletService_ChageAmount_Call {
	_c.Call.Return(wallet1, err)
	return _c
}

func (_c *MockWalletService_ChageAmount_Call) RunAndReturn(run func(context1 context.Context, walletRequest wallet.WalletRequest) (wallet.Wallet, error)) *MockWalletService_ChageAmount_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalanceByID provides a mock function for the type MockWalletService
func (_mock *MockWalletService) GetBalanceByID(s string) (float64, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceByID")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletService_GetBalanceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceByID'
type MockWalletService_GetBalanceByID_Call struct {
	*mock.Call
}

// GetBalanceByID is a helper method to define mock.On call
//   - s string
func (_e *MockWalletService_Expecter) GetBalanceByID(s any) *MockWalletService_GetBalanceByID_Call {
	return &MockWalletService_GetBalanceByID_Call{Call: _e.mock.On("GetBalanceByID", s)}
}

func (_c *MockWalletService_GetBalanceByID_Call) Run(run func(s string)) *MockWalletService_GetBalanceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWalletService_GetBalanceByID_Call) Return(f float64, err error) *MockWalletService_GetBalanceByID_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockWalletService_GetBalanceByID_Call) RunAndReturn(run func(s string) (float64, error)) *MockWalletService_GetBalanceByID_Call {
	_c.Call.Return(run)
	return _c
}
