// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"exampleApp/internal/domain/wallet"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddOrUpdateWallet provides a mock function for the type MockRepository
func (_mock *MockRepository) AddOrUpdateWallet(ctx context.Context, w wallet.WalletRequest) (wallet.Wallet, error) {
	ret := _mock.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for AddOrUpdateWallet")
	}

	var r0 wallet.Wallet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, wallet.WalletRequest) (wallet.Wallet, error)); ok {
		return returnFunc(ctx, w)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, wallet.WalletRequest) wallet.Wallet); ok {
		r0 = returnFunc(ctx, w)
	} else {
		r0 = ret.Get(0).(wallet.Wallet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, wallet.WalletRequest) error); ok {
		r1 = returnFunc(ctx, w)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_AddOrUpdateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrUpdateWallet'
type MockRepository_AddOrUpdateWallet_Call struct {
	*mock.Call
}

// AddOrUpdateWallet is a helper method to define mock.On call
//   - ctx context.Context
//   - w wallet.WalletRequest
func (_e *MockRepository_Expecter) AddOrUpdateWallet(ctx any, w any) *MockRepository_AddOrUpdateWallet_Call {
	return &MockRepository_AddOrUpdateWallet_Call{Call: _e.mock.On("AddOrUpdateWallet", ctx, w)}
}

func (_c *MockRepository_AddOrUpdateWallet_Call) Run(run func(ctx context.Context, w wallet.WalletRequest)) *MockRepository_AddOrUpdateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 wallet.WalletRequest
		if args[1] != nil {
			arg1 = args[1].(wallet.WalletRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_AddOrUpdateWallet_Call) Return(wallet1 wallet.Wallet, err error) *MockRepository_AddOrUpdateWallet_Call {
	_c.Call.Return(wallet1, err)
	return _c
}

func (_c *MockRepository_AddOrUpdateWallet_Call) RunAndReturn(run func(ctx context.Context, w wallet.WalletRequest) (wallet.Wallet, error)) *MockRepository_AddOrUpdateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalanceByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetBalanceByID(uuid string) (float64, error) {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetBalanceByID")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (float64, error)); ok {
		return returnFunc(uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) float64); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetBalanceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalanceByID'
type MockRepository_GetBalanceByID_Call struct {
	*mock.Call
}

// GetBalanceByID is a helper method to define mock.On call
//   - uuid string
func (_e *MockRepository_Expecter) GetBalanceByID(uuid any) *MockRepository_GetBalanceByID_Call {
	return &MockRepository_GetBalanceByID_Call{Call: _e.mock.On("GetBalanceByID", uuid)}
}

func (_c *MockRepository_GetBalanceByID_Call) Run(run func(uuid string)) *MockRepository_GetBalanceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetBalanceByID_Call) Return(f float64, err error) *MockRepository_GetBalanceByID_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockRepository_GetBalanceByID_Call) RunAndReturn(run func(uuid string) (float64, error)) *MockRepository_GetBalanceByID_Call {
	_c.Call.Return(run)
	return _c
}
